url: https://sarahparkerpt.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Sarah Parker PT
email: your-email@domain.com
description: "My aim is to teach and educate people on how to live a well-rounded and balanced lifestyle. I strive to help you achieve your goals with full guidance both in and outside our sessions. My continuing support aims to ensure you are on track and have the knowledge you need to succeed. I will guide you along the way to ensure your new healthy routine is achievable and sustainable."


# Team names, titles and social links
people:
- name: Sarah Parker
  pic: 1
  position: Personal Trainer
  social:
    - title: instagram
      url: https://www.instagram.com/sarahparker_pt/
    - title: facebook
      url: https://www.facebook.com/sarahparkerpt/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/sarahparker_pt/
  - title: facebook
    url: https://www.facebook.com/sarahparkerpt/

# Postal address (add as many lines as necessary)
address:
  - line: Basingstoke, Hampshire

# Build settings
markdown: kramdown
permalink: pretty
