url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Sarah Parker PT
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Sarah Parker
  pic: 1
  position: Personal Trainer
  social:
    - title: instagram
      url: https://www.instagram.com/sarahparker_pt/
    - title: facebook
      url: https://www.facebook.com/sarahparkerpt/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/sarahparker_pt/
  - title: facebook
    url: https://www.facebook.com/sarahparkerpt/

# Postal address (add as many lines as necessary)
address:
  - line: Basingstoke, Hampshire

# Build settings
markdown: kramdown
permalink: pretty
